### ISSUE TITLE
RUST_TAG in wdk-alloc

### ISSUE THREAD

**Issue by Xiphoseer** [microsoft/windows-drivers-rs#12]
https://github.com/microsoft/windows-drivers-rs/blob/79d09bbc2f42a8cc0f2f1b47f2bb3839e232e3b0/crates/wdk-alloc/src/lib.rs#L25-L33

Is there a reason this uses lazy_static instead of just a const and a byte string literal (of type `&[u8;4]`)? [`u32::from_ne_bytes`](https://doc.rust-lang.org/stable/core/primitive.u32.html#method.from_ne_bytes) is const stable since 1.44.

C.f. https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=2be24215859c818308542b6893f36ca2

**Comment by jxy-s** [comment]
In general on on use of `lazy_static!`. Something that I doubt is considered by the `lazy_static` crate, or the standard Rust libraries in general, is interrupts that end up preempting code execution. An example of this is APC delivery preempting some region of code that expects not to be interrupted.

For example, APC delivery could preempt some control flow. Most synchronization schemes or primitives in the kernel require you to call [KeEnterCriticalRegion](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/ntddk/nf-ntddk-keentercriticalregion) and [KeLeaveCriticalRegion](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/ntddk/nf-ntddk-keleavecriticalregion).
