### ISSUE TITLE
Need install wdk?

### ISSUE THREAD

**Issue by Richyeoh** [microsoft/windows-drivers-rs#126]
Error: failed to run custom build command for `wdk-sys v0.2.0`

Caused by:
  process didn't exit successfully: `D:\Myself\RustProjects\wdk-rs\target\debug\build\wdk-sys-d4ff924bcbc978d5\build-script-build` (exit code: 1)
  --- stderr
  Error: 系统找不到指定的路径。 (os error 3)

**Comment by wmmc88** [comment]
Please refer to the build requirements in the readme: https://github.com/microsoft/windows-drivers-rs?tab=readme-ov-file#build-requirements
