### ISSUE TITLE
The readme misses some config parameter for "cargo new" 

### ISSUE THREAD

**Issue by mhandb** [microsoft/windows-drivers-rs#15]
https://github.com/microsoft/windows-drivers-rs/blob/e127a84a90e63d4f124177960d45785d78839ded/README.md?plain=1#L39
`--config` needs a `KEY=VALUE`

**Comment by wmmc88** [comment]
Hi @mhandb. This is a typo in the readme. `--config` is not needed.

**Comment by shymega** [comment]
Hey @wmmc88 - would you be open to a PR removing that option in the README?

**Comment by wmmc88** [comment]
Yup. Theres some Readme updates I need to make and will be opening a PR later today.

**Comment by shymega** [comment]
> Theres some other Readme updates I need to make and I will be opening a PR later today to resolve this.

No worries - I'll leave the change up to you, then. I've looked at that PR and it looks good!
