### ISSUE TITLE
Minor bug in `build.rs` content provided by README

### ISSUE THREAD

**Issue by kedom1337** [microsoft/windows-drivers-rs#187]
The section of the README describing how to create a new `windows-driver-rs` project has a minor bug in step 6.
It provides the following code for the `build.rs` file.

```rust
fn main() -> Result<(), wdk_build::ConfigError> {
   wdk_build::Config::from_env_auto()?.configure_binary_build()?;
   Ok(())
}
``` 
The issue here is the last `?` after `configure_binary_build`. This function returns `()` and therefore does not implement `Try` which results in an error. Simply removing the last `?` resolves the issue.

**Comment by wmmc88** [comment]
This is not an error. the README is for top of tree, which made a breaking change to that function. There are changes on main that are not yet released to crates.io.

See [this](https://github.com/microsoft/windows-drivers-rs/pull/178#issuecomment-2186980504) for more details.
