### ISSUE TITLE
cannot find function `configure_binary_build` in crate `wdk_build` not found in `wdk_build`

### ISSUE THREAD

**Issue by Escandiuzzi** [microsoft/windows-drivers-rs#206]
I'm following the steps in the "Getting Started" chapter but I'm getting an error with wdk_build crate "cannot find function `configure_binary_build` in crate `wdk_build` not found in `wdk_build`" in build.rs file.

My build.rs file looks like this

`fn main() -> Result<(), wdk_build::ConfigError> {
   wdk_build::configure_binary_build()
}`

Am I missing something?

**Comment by wmmc88** [comment]
If you are following the Getting Started in main branch, it corresponds with code in the main branch (currently not released to crates.io yet). Either use the git tag for `0.2.0` to read the docs for that released version of the crates, or use the latest via a [cargo git dependency](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-git-repositories). If you go the git dependency route, you should pin to a `rev`.

Just an FYI that the latest main code has quite a few improvements and major changes.

**Comment by Escandiuzzi** [comment]
Cool! That makes sense :)

Thank you!
