### ISSUE TITLE
cloning windows-drivers-rs and modifying the config specified in build.rs of wdk-sys

### ISSUE THREAD

**Issue by lfern** [microsoft/windows-drivers-rs#54]
I would like to create a UMDF2 driver. I have cloned this repo but I am not able to modify the build.rs of wdk-sys crate to compile this umdf driver. Could you help me with how to do it? Thanks!!!

**Comment by wmmc88** [comment]
Source modification is no longer needed since #186 . See the new `[package.metadata.wdk.driver-model]` configuration in the README :)
